/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const isDark: typeof import('./src/utils/dark')['isDark']
  const setupCounter: typeof import('./src/setups/count')['setupCounter']
  const setupToggleDark: typeof import('./src/setups/toggleDark')['setupToggleDark']
  const toggleDark: typeof import('./src/utils/dark')['toggleDark']
}
