/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const isDark: typeof import('./utils/dark')['isDark']
  const setupCounter: typeof import('./setups/count')['setupCounter']
  const setupDarker: typeof import('./setups/dark')['setupDarker']
  const toggleDark: typeof import('./utils/dark')['toggleDark']
}
